gantt
    dateFormat  YYYY-MM-DD
    title       B2 English Study Progress (May 2026)

    section Core Grammar - Tracked Progress
    Lack of Necessity ('no need to' / 'don't need to')  :id1, 2026-05-14, 2d
    Verb Patterns: Gerunds after 'consider'            :id2, 2026-05-14, 2d
    Modals - Necessity (8.2)                           :id3, 2026-05-15, 3d
    Past Perfect w/ Conjunctions ('before'/'until')    :id4, 2026-05-16, 2d

    section Pronouns & Determiners
    Possessive & Reflexive Pronouns                   :id5, 2026-05-10, 2d
    Determiners & Pronouns                            :id6, 2026-05-11, 2d
    Quantifiers                                       :id7, 2026-05-12, 1d
    Pronouns & Demonstratives                         :id8, 2026-05-12, 1d

    section Conditionals & Verb Structures
    Conditionals (General)                            :id9, 2026-05-12, 2d
    Mixed Conditionals                                :id10, 2026-05-14, 2d
    Causative & Object Infinitives                    :id11, 2026-05-11, 2d
    Verb Patterns - Gerunds (General)                 :id12, 2026-05-14, 2d
    Possessive Gerunds                                :id13, 2026-05-15, 1d

    section Other Key Grammar & Usage
    Dependent Prepositions                            :id14, 2026-05-10, 2d
    Reported Speech                                   :id15, 2026-05-13, 2d
    Comparisons ('as...as')                           :id16, 2026-05-15, 1d
    Order of Adjectives                               :id17, 2026-05-16, 1d
    Conjunctions ('although/though/even though')      :id18, 2026-05-14, 1d
    Differentiating 'every'/'each'                    :id19, 2026-05-15, 1d
    Preferences ('prefer'/'rather')                   :id20, 2026-05-16, 1d
    'It be pointless' & Relative Clauses              :id21, 2026-05-17, 2d
    Word Focus (7.8)                                  :id22, 2026-05-17, 1d
    Use of English (Session 7.3)                      :id23, 2026-05-17, 1d
